version: "3.8"

services:
  server:
    build:
      context: .
    ports:
      - "80:80"  # Mở port 80 của container ra port 9000 trên host
    volumes:
      - ./src:/var/www/html  # Gắn kết thư mục source code vào container
    environment:
      - DB_HOST=db  # Tên service DB từ docker-compose
      - DB_NAME=work7  # Tên cơ sở dữ liệu mới
      - DB_USER=root  # Tên người dùng database
      - DB_PASSWORD=rootpassword  # Mật khẩu cơ sở dữ liệu trực tiếp
    depends_on:
      - db  # Đảm bảo DB khởi động trước

  db:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword  # Mật khẩu root cho MariaDB
      - MARIADB_DATABASE=work7  # Tên cơ sở dữ liệu ban đầu thay vì 'example'
    volumes:
      - db-data:/var/lib/mysql  # Volume lưu trữ dữ liệu của MariaDB
    expose:
      - "3306"  # Mở port 3306 để các service khác có thể kết nối
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "80:80"  # Mở giao diện phpMyAdmin trên port 8080
    environment:
      - PMA_HOST=db  # Tên service của MariaDB trong docker-compose
    depends_on:
      - db  # Đảm bảo DB có sẵn trước khi phpMyAdmin khởi động

volumes:
  db-data:
